### ISSUE TITLE
moduleRoutes through ugly big red warning

### ISSUE THREAD

**Issue by ffugly** [fugitivelabs/yote-react#41]
```
react-bundle.js:1145 Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <Route>. See https://fb.me/react-warning-keys for more information.
```

Need a way to pass in keys like `<Route key={i} path="..." />`

May want to look at React-Router's [dynamic routing docs](https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md) and also their "huge app" [example](https://github.com/reactjs/react-router/tree/master/examples/huge-apps) which would likely solve the issue, but significantly increase boilerplate code

**Comment by grantfowler** [comment]
fixed in #65
